services:
  - type: web
    name: somos-venia-chatbot-redes-sociales
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_DB_URL
        sync: false
      - key: META_VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: FACEBOOK_PAGE_TOKEN
        sync: false
